# Generated by Django 6.0.3 on 2026-03-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0004_loginotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['stage', 'order', 'id']},
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1), ('order__lte', 25)), name='question_order_between_1_and_25'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('stage_ref__isnull', False)), fields=('stage_ref', 'order'), name='unique_stage_ref_question_order'),
        ),
    ]
