# Generated by Django 6.0.3 on 2026-03-30 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0008_assessment_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='competency.assessmentcycle'),
        ),
    ]
