# Generated by Django 6.0.3 on 2026-03-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0009_alter_assessment_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcycle',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
